// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const envUrl = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const envKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

/** When unset (e.g. GitHub Pages static build), the app still boots; auth/DB are disabled. */
export const isSupabaseConfigured = Boolean(
  envUrl && envKey && envUrl.length > 0 && envKey.length > 0
);

// Valid-shaped placeholders so createClient() never throws; real keys come from .env in dev.
const placeholderUrl = "https://public.supabase.co";
const placeholderKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU";

export const supabase = createClient<Database>(
  isSupabaseConfigured ? (envUrl as string) : placeholderUrl,
  isSupabaseConfigured ? (envKey as string) : placeholderKey,
  {
    auth: {
      storage: localStorage,
      persistSession: isSupabaseConfigured,
      autoRefreshToken: isSupabaseConfigured,
    },
  }
);